[package]
name = "bip32"
version = "0.5.1"
description = """
BIP32 hierarchical key derivation implemented in a generic, no_std-friendly
manner. Supports deriving keys using the pure Rust curve25519_dalek crate
"""
authors = ["Tony Arcieri <tony@iqlusion.io>"]
license = "Apache-2.0 OR MIT"
homepage = "https://github.com/iqlusioninc/crates/"
repository = "https://github.com/iqlusioninc/crates/tree/main/bip32"
categories = ["cryptography", "no-std"]
keywords = ["crypto", "bip32", "bip39", "derivation", "mnemonic"]
readme = "README.md"
edition  = "2021"
rust-version = "1.65"

[dependencies]
bs58 = { version = "0.5", default-features = false, features = ["check"] }
hmac = { version = "0.12", default-features = false }
rand_core = { version = "0.6", default-features = false }
ripemd = { version = "0.1", default-features = false }
sha2 = { version = "0.10", default-features = false }
subtle = { version = "2", default-features = false }
zeroize = { version = "1", default-features = false }

# optional dependencies
once_cell = { version = "1", optional = true }
pbkdf2 = { version = "0.12", optional = true, default-features = false, features = ["hmac"] }
curve25519-dalek = { version = "3", optional = true, features = ["serde"] }

[dev-dependencies]
hex-literal = "0.4"
rand_core = { version = "0.6", features = ["std"] }

[features]
default = ["bip39", "ed25519", "std"]
alloc = ["zeroize/alloc"]
bip39 = ["mnemonic", "pbkdf2", "std"]
mnemonic = ["alloc", "once_cell"]
ed25519 = ["curve25519-dalek"]
std = ["alloc"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
