[package]
name = "entity"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "entity"
path = "lib.rs"

[dependencies]
rocket = { version = "0.5.0-rc.2", features = [ "json" ] }

[dependencies.sea-orm]
version = "0.11.0" # sea-orm version
